### ISSUE TITLE
Build script stuck at 92%

### ISSUE THREAD

**Issue by KorbinianK** [xxhomey19/bootstrap-webpack-jquery-boilerplate#1]
Wanted to have a look at this boilerplate as I was in the process of trying to set one up as well. However when I run `npm run build` it get's stuck after a while at ` 92% chunk asset optimization UglifyJSPlugin`.

Even after several minutes it does not get past this point. I didn't change anything, just did `git clone` and `npm install` before.

**Comment by xxhomey19** [comment]
Hi @KorbinianK 
Could you supply your node and npm version?
I'm using node v10.3.0 and npm v6.1.0, and it's all good.

**Comment by KorbinianK** [comment]
Hi. I also have node 10.3 and npm 6.1. Tried a few things I found through Google, seems others have issues with that plugin as well, but no success so far.

OS: Win10 SCU + WSL (Ubuntu 16.04)

**Comment by xxhomey19** [comment]
Hey, I have disabled the option `sourceMap`, and I hope this could solve the problem for you. Could you pull master and run it again? Thanks!

**Comment by xxhomey19** [comment]
Would it be memory problem? Or I can't figure out any other possibilities sorry.

**Comment by xxhomey19** [comment]
Closed due to inactivity.
