### ISSUE TITLE
Great Boilerplate

### ISSUE THREAD

**Issue by johndavemanuel** [xxhomey19/bootstrap-webpack-jquery-boilerplate#10]
Do you have any tutorial for this on how to setup this from scratch?

**Comment by xxhomey19** [comment]
hmmm... basically I just try to put JavaScript, jQuery and Bootstrap together by Webpack, so the main effort is working on the Webpack configuration. It takes a while to play around with those loaders and read official docs. As for ESLint and Prettier, most of those configs are copied from my other repos, and generally you can find lots of examples on GitHub. I don't intend to make this boilerplate too complex, so it just includes some fundamental stuff. Hope this helps you.

**Comment by johndavemanuel** [comment]
Great! I will check those things! Thanks!
