### ISSUE TITLE
 Module build failed

### ISSUE THREAD

**Issue by QiZhongdd** [xxhomey19/bootstrap-webpack-jquery-boilerplate#9]
ERROR in ./src/public/images/image_3.jpg
    Module build failed (from ./node_modules/image-webpack-loader/index.js):
    Error: write EOF
        at WriteWrap.afterWrite [as oncomplete] (net.js:868:14)
     @ ./src/page/index.html (./node_modules/html-webpack-plugin/lib/loader.js!./src/page/index.html) 1:2683-2724

    ERROR in ./src/public/images/image_2.jpg
    Module build failed (from ./node_modules/image-webpack-loader/index.js):
    Error: write EOF
        at WriteWrap.afterWrite [as oncomplete] (net.js:868:14)
     @ ./src/page/index.html (./node_modules/html-webpack-plugin/lib/loader.js!./src/page/index.html) 1:2196-2237

    ERROR in ./src/public/images/image_1.jpg
    Module build failed (from ./node_modules/image-webpack-loader/index.js):
    Error: write EOF
        at WriteWrap.afterWrite [as oncomplete] (net.js:868:14)
     @ ./src/page/index.html (./node_modules/html-webpack-plugin/lib/loader.js!./src/page/index.html) 1:1698-1739

**Comment by xxhomey19** [comment]
Hi @QiZhongdd 
Could you describe these errors with more detailed descriptions? Like what situation will cause this problem. Thanks.

**Comment by xxhomey19** [comment]
Closed due to inactivity.
